<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>v</string>
    </array>
    <key>name</key>
    <string>Coq</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>variable.source.coq</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(Axiom|Conjecture|Parameter|Parameters|Variable|Variables|Hypothesis|Hypotheses|Definition|Let|Fixpoint|CoFixpoint|Inductive|CoInductive|Remark|Fact|Corollary|Proposition|Example|Module|Theorem|Lemma)\b</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.source.coq</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(Require|Proof|Qed|Type|Admitted|match|with|end|Eval|in|Check|End|Notation|forall|as|Defined|Set|fun|at|cofix|else|exists|exists2|fix|for|if|IF|let|mod|Prop|return|then|using|where|Abort)\b</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>\(\*</string>
            <key>end</key>
            <string>\*\)</string>
            <key>name</key>
            <string>comment.source.coq</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.coq</string>
    <key>uuid</key>
    <string>f3924813-f5ba-4ccf-b76f-f9bff62c5180</string>
</dict>
</plist>
